export const GET_EMPLOYEES_LIST_REQUESTED = 'GET_EMPLOYEES_LIST_REQUESTED';
export const GET_EMPLOYEES_LIST_SUCCESS = 'GET_EMPLOYEES_LIST_SUCCESS';
export const GET_EMPLOYEES_LIST_FAIL = 'GET_EMPLOYEES_LIST_FAIL';

export const ADD_EMPLOYEE_TO_LIST = 'ADD_EMPLOYEE_TO_LIST';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
